pekko {
  actor {
    provider = "cluster"
    serialization-bindings {
      "io.github.nicolasfara.es01.cluster.CborSerializable" = jackson-cbor
    }
  }
  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      port = 2551
    }
  }

  cluster { }
}