services:
  seed:
    build:
      context: ../
      dockerfile: docker/Dockerfile.coordinator
    ports:
      - "1600:1600"
    environment:
      - CLUSTER_IP=seed
      - CLUSTER_PORT=1600
      - SEED_PORT_1600_TCP_ADDR=seed

  worker1:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    # ports:
    #   - "2552:2551"
    environment:
      - CLUSTER_IP=worker1
      - CLUSTER_PORT=2552
      - SEED_PORT_1600_TCP_ADDR=seed

  worker2:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    # ports:
    #   - "2553:2551"
    environment:
      - CLUSTER_IP=worker2
      - CLUSTER_PORT=2553
      - SEED_PORT_1600_TCP_ADDR=seed